### ISSUE TITLE
As an author I want to make posts.

### ISSUE THREAD

**Issue by Hreherch** [i-5ive/cmput404-project#11]
1. As an author, posts I create be private to me
2. As an author, posts I create be private to another author
3. As an author, posts I create be private to my friends
4. As an author, posts I create be private to friends of friends
5. As an author, posts I create be private to only friends on my host
6. As an author, posts I create can be public
7. As an author, posts I make can be in simple plain text
8. As an author, posts I make can be in markdown (commonMark is good)

These should be toggleAble within the make post

**Comment by chaitali** [comment]
Should be done :)
