### ISSUE TITLE
As an author, I want to be able to make posts that are unlisted, that are publicly shareable by URI alone (or for embedding images)

### ISSUE THREAD

**Issue by MandyMeindersma** [i-5ive/cmput404-project#29]

**Comment by Hreherch** [comment]
Like unlisted youtube video

**Comment by Hreherch** [comment]
or when you upload a github image

**Comment by amalik2** [comment]
By publicly shareable, does it mean anyone with the link can access it, regardless of the visibility option selected?

**Comment by Hreherch** [comment]
It makes more sense for it to require the same permission levels
It's like when you share a Google doc with a link but limit it to "only the company" (i.e. intuit or UofA) so that just anyone can't get the link and see the thing you've shared
