### ISSUE TITLE
As an author, I want to feel safe about sharing images and posts with my friends – images should not publicly accessible without authentication.

### ISSUE THREAD

**Issue by cmackenzie1** [i-5ive/cmput404-project#4]

**Comment by Hreherch** [comment]
see: 
 - [ ] Enforce some authentication (Consider HTTP Basic Auth) 

from: https://github.com/abramhindle/CMPUT404-project-socialdistribution/blob/master/project.org

**Comment by cmackenzie1** [comment]
Backend in #43. @MandyMeindersma want to do the frontend jazz?

**Comment by MandyMeindersma** [comment]
On it! :)

**Comment by chaitali** [comment]
This still isn't done, when you aren't logged in images are still visible in the discover feed -- will need to complete

**Comment by MandyMeindersma** [comment]
lol sorry, chaitali did more work than me
