### ISSUE TITLE
As an author, I want un-befriend local and remote authors

### ISSUE THREAD

**Issue by cmackenzie1** [i-5ive/cmput404-project#6]

**Comment by MandyMeindersma** [comment]
@amalik2  don't you already have this done? https://github.com/i-5ive/cmput404-project/blob/master/react/src/js/react/profile/ProfileStore.js#L253

**Comment by amalik2** [comment]
@MandyMeindersma This isn't implemented for remote authors, so it should not be closed

**Comment by Hreherch** [comment]
Yea
