### ISSUE TITLE
Examples + description for API documentation

### ISSUE THREAD

**Issue by amalik2** [i-5ive/cmput404-project#96]

**Comment by MandyMeindersma** [comment]
Examples are done. https://github.com/i-5ive/cmput404-project/wiki/User-Manual

**Comment by MandyMeindersma** [comment]
link to api in wiki: https://github.com/i-5ive/cmput404-project/wiki/API-Documentation

**Comment by MandyMeindersma** [comment]
the ta's also said:
```Documentation of API should say what the APIs do and give some sort of example and example of response -- Should not assume that users know specs etc. ex. GET /users/{id}/ Function: Grabs users of ...etc.```

**Comment by MandyMeindersma** [comment]
there is SOOOO much written in the wiki. WE DID GOOD FAM
