### ISSUE TITLE
TA feedback

### ISSUE THREAD

**Issue by amalik2** [i-5ive/cmput404-project#98]
Could not see new “friends only” post by author 6 (michael) that is friends with bhart

Could not see FAOF posts

Returned error for http --auth bhart:password GET
https://weeb-tears.herokuapp.com/author/posts/

**Comment by amalik2** [comment]
GET https://weeb-tears.herokuapp.com/author/posts/ works now

**Comment by MandyMeindersma** [comment]
![image](https://user-images.githubusercontent.com/17459171/55704781-49d45a80-599a-11e9-9f7d-36ac4d786be2.png)
????

**Comment by cmackenzie1** [comment]
@MandyMeindersma I would say that's OK. We don't necessarily want to see a FOAF post in our feed, but would like to see it if we view their profile. Like how FB does it.

**Comment by MandyMeindersma** [comment]
Lol I didn't read Ben's pull request though, it should work now in feed

**Comment by MandyMeindersma** [comment]
![image](https://user-images.githubusercontent.com/17459171/55739778-f63c2e00-59e6-11e9-8b8d-691aa5ad86bc.png)
